package model.entity;
// Generated 2016-12-08 01:23:57 by Hibernate Tools 5.1.0.Alpha1

/**
 * Address generated by hbm2java
 */
public class Address extends Entity {
	private static final long serialVersionUID = 2468964352462559357L;
	private Integer addressId;
	private String addressCity;
	private String addressStreet;
	private String addressCode;

	
	public Address() {}
	public Address(String addressCity, String addressStreet, String addressCode) {
		this.addressCity = addressCity;
		this.addressStreet = addressStreet;
		this.addressCode = addressCode;
	}

	
	public Integer getAddressId() {
		return this.addressId;
	}
	public void setAddressId(Integer addressId) {
		this.addressId = addressId;
	}
	public String getAddressCity() {
		return this.addressCity;
	}
	public void setAddressCity(String addressCity) {
		this.addressCity = addressCity;
	}
	public String getAddressStreet() {
		return this.addressStreet;
	}
	public void setAddressStreet(String addressStreet) {
		this.addressStreet = addressStreet;
	}
	public String getAddressCode() {
		return this.addressCode;
	}
	public void setAddressCode(String addressCode) {
		this.addressCode = addressCode;
	}
}