package model.entity;
// Generated 2016-12-08 01:23:57 by Hibernate Tools 5.1.0.Alpha1

/**
 * BankId generated by hbm2java
 */
public class BankId implements java.io.Serializable {
	private static final long serialVersionUID = -1793326229734023668L;
	private int bankId;
	private int studentId;

	
	public BankId() {}
	public BankId(int bankId, int studentId) {
		this.bankId = bankId;
		this.studentId = studentId;
	}

	
	public int getBankId() {
		return this.bankId;
	}
	public void setBankId(int bankId) {
		this.bankId = bankId;
	}
	public int getStudentId() {
		return this.studentId;
	}
	public void setStudentId(int studentId) {
		this.studentId = studentId;
	}
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BankId))
			return false;
		BankId castOther = (BankId) other;

		return (this.getBankId() == castOther.getBankId()) && (this.getStudentId() == castOther.getStudentId());
	}
	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getBankId();
		result = 37 * result + this.getStudentId();
		return result;
	}
}