package model.entity;
// Generated 2016-12-08 01:23:57 by Hibernate Tools 5.1.0.Alpha1

/**
 * Bank generated by hbm2java
 */
public class Bank implements java.io.Serializable {
	private static final long serialVersionUID = -2966570014951439379L;
	private BankId id;
	private String bankNumber;

	
	public Bank() {}
	public Bank(BankId id) {
		this.id = id;
	}
	public Bank(BankId id, String bankNumber) {
		this.id = id;
		this.bankNumber = bankNumber;
	}
	public Bank(int bankId, int studentId, String bankNumber) {
		this.id = new BankId(bankId, studentId);
		this.bankNumber = bankNumber;
	}

	
	public BankId getId() {
		return this.id;
	}
	public void setId(BankId id) {
		this.id = id;
	}
	public String getBankNumber() {
		return this.bankNumber;
	}
	public void setBankNumber(String bankNumber) {
		this.bankNumber = bankNumber;
	}
}