package model.entity;
// Generated 2016-12-08 01:23:57 by Hibernate Tools 5.1.0.Alpha1

/**
 * Certificate generated by hbm2java
 */
public class Certificate implements java.io.Serializable {
	private static final long serialVersionUID = 2539929666796043408L;
	private CertificateId id;
	private String certificateName;

	
	public Certificate() {}
	public Certificate(CertificateId id) {
		this.id = id;
	}
	public Certificate(CertificateId id, String certificateName) {
		this.id = id;
		this.certificateName = certificateName;
	}
	public Certificate(int certificateId, int teacherId, String certificateName) {
		this.id = new CertificateId(certificateId, teacherId);
		this.certificateName = certificateName;
	}

	
	public CertificateId getId() {
		return this.id;
	}
	public void setId(CertificateId id) {
		this.id = id;
	}
	public String getCertificateName() {
		return this.certificateName;
	}
	public void setCertificateName(String certificateName) {
		this.certificateName = certificateName;
	}
}