package model.entity;
// Generated 2016-12-08 01:23:57 by Hibernate Tools 5.1.0.Alpha1

/**
 * CertificateId generated by hbm2java
 */
public class CertificateId implements java.io.Serializable {
	private static final long serialVersionUID = 6290477574262257555L;
	private int certificateId;
	private int teacherId;

	
	public CertificateId() {}
	public CertificateId(int certificateId, int teacherId) {
		this.certificateId = certificateId;
		this.teacherId = teacherId;
	}

	
	public int getCertificateId() {
		return this.certificateId;
	}
	public void setCertificateId(int certificateId) {
		this.certificateId = certificateId;
	}
	public int getTeacherId() {
		return this.teacherId;
	}
	public void setTeacherId(int teacherId) {
		this.teacherId = teacherId;
	}
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CertificateId))
			return false;
		CertificateId castOther = (CertificateId) other;

		return (this.getCertificateId() == castOther.getCertificateId())
				&& (this.getTeacherId() == castOther.getTeacherId());
	}
	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCertificateId();
		result = 37 * result + this.getTeacherId();
		return result;
	}
}