package model.entity;
// Generated 2016-12-08 01:23:57 by Hibernate Tools 5.1.0.Alpha1

/**
 * Course generated by hbm2java
 */
public class Course extends Entity {
	private static final long serialVersionUID = 2445243415455459274L;
	private Integer courseId;
	private String courseName;
	private String courseForm;
	private Integer courseTerm;
	private Integer fieldOfStudyId;

	
	public Course() {}
	public Course(String courseName, String courseForm, Integer courseTerm, Integer fieldOfStudyId) {
		this.courseName = courseName;
		this.courseForm = courseForm;
		this.courseTerm = courseTerm;
		this.fieldOfStudyId = fieldOfStudyId;
	}

	
	public Integer getCourseId() {
		return this.courseId;
	}
	public void setCourseId(Integer courseId) {
		this.courseId = courseId;
	}
	public String getCourseName() {
		return this.courseName;
	}
	public void setCourseName(String courseName) {
		this.courseName = courseName;
	}
	public Integer getCourseTerm() {
		return this.courseTerm;
	}
	public void setCourseTerm(Integer courseTerm) {
		this.courseTerm = courseTerm;
	}
	public Integer getFieldOfStudyId() {
		return fieldOfStudyId;
	}
	public void setFieldOfStudyId(Integer fieldOfStudyId) {
		this.fieldOfStudyId = fieldOfStudyId;
	}
	public String getCourseForm() {
		return courseForm;
	}
	public void setCourseForm(String courseForm) {
		this.courseForm = courseForm;
	}
}