package model.entity;
// Generated 2016-12-08 01:23:57 by Hibernate Tools 5.1.0.Alpha1

/**
 * CourseFormId generated by hbm2java
 */
public class CourseFormId implements java.io.Serializable {
	private static final long serialVersionUID = 7134618224694739590L;
	private int courseFormId;
	private int courseId;

	
	public CourseFormId() {}
	public CourseFormId(int courseFormId, int courseId) {
		this.courseFormId = courseFormId;
		this.courseId = courseId;
	}

	
	public int getCourseFormId() {
		return this.courseFormId;
	}
	public void setCourseFormId(int courseFormId) {
		this.courseFormId = courseFormId;
	}
	public int getCourseId() {
		return this.courseId;
	}
	public void setCourseId(int courseId) {
		this.courseId = courseId;
	}
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CourseFormId))
			return false;
		CourseFormId castOther = (CourseFormId) other;

		return (this.getCourseFormId() == castOther.getCourseFormId())
				&& (this.getCourseId() == castOther.getCourseId());
	}
	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCourseFormId();
		result = 37 * result + this.getCourseId();
		return result;
	}
}