package model.entity;
// Generated 2016-12-08 01:23:57 by Hibernate Tools 5.1.0.Alpha1

/**
 * CourseForm generated by hbm2java
 */
public class CourseForm implements java.io.Serializable {
	private static final long serialVersionUID = 1483422545373205211L;
	private CourseFormId id;
	private String courseForm;

	
	public CourseForm() {}
	public CourseForm(CourseFormId id) {
		this.id = id;
	}
	public CourseForm(CourseFormId id, String courseForm) {
		this.id = id;
		this.courseForm = courseForm;
	}
	public CourseForm(int courseFormId, int courseId, String courseForm) {
		this.id = new CourseFormId(courseFormId, courseId);
		this.courseForm = courseForm;
	}

	
	public CourseFormId getId() {
		return this.id;
	}
	public void setId(CourseFormId id) {
		this.id = id;
	}
	public String getCourseForm() {
		return this.courseForm;
	}
	public void setCourseForm(String courseForm) {
		this.courseForm = courseForm;
	}
}