package model.entity;
// Generated 2016-12-08 01:23:57 by Hibernate Tools 5.1.0.Alpha1

/**
 * Department generated by hbm2java
 */
public class Department implements java.io.Serializable {
	private static final long serialVersionUID = 3430559057774407595L;
	private Integer departmentId;
	private String departmentName;
	private String departmentBuilding;
	private String departmentDescription;

	
	public Department() {}
	public Department(String departmentName, String departmentBuilding, String departmentDescription) {
		this.departmentName = departmentName;
		this.departmentBuilding = departmentBuilding;
		this.departmentDescription = departmentDescription;
	}

	
	public Integer getDepartmentId() {
		return this.departmentId;
	}
	public void setDepartmentId(Integer departmentId) {
		this.departmentId = departmentId;
	}
	public String getDepartmentName() {
		return this.departmentName;
	}
	public void setDepartmentName(String departmentName) {
		this.departmentName = departmentName;
	}
	public String getDepartmentBuilding() {
		return this.departmentBuilding;
	}
	public void setDepartmentBuilding(String departmentBuilding) {
		this.departmentBuilding = departmentBuilding;
	}
	public String getDepartmentDescription() {
		return this.departmentDescription;
	}
	public void setDepartmentDescription(String departmentDescription) {
		this.departmentDescription = departmentDescription;
	}
}