package model.entity;
// Generated 2016-12-08 01:23:57 by Hibernate Tools 5.1.0.Alpha1

/**
 * Specialization generated by hbm2java
 */
public class Specialization implements java.io.Serializable {
	private static final long serialVersionUID = -4323862111904696752L;
	private SpecializationId id;
	private String specializationName;

	
	public Specialization() {}
	public Specialization(SpecializationId id) {
		this.id = id;
	}
	public Specialization(SpecializationId id, String specializationName) {
		this.id = id;
		this.specializationName = specializationName;
	}
	public Specialization(int specializationId, int fieldOfStudyId, String specializationName) {
		this.id = new SpecializationId(specializationId, fieldOfStudyId);
		this.specializationName = specializationName;
	}

	
	public SpecializationId getId() {
		return this.id;
	}
	public void setId(SpecializationId id) {
		this.id = id;
	}
	public String getSpecializationName() {
		return this.specializationName;
	}
	public void setSpecializationName(String specializationName) {
		this.specializationName = specializationName;
	}
}