package model.entity;
// Generated 2016-12-08 01:23:57 by Hibernate Tools 5.1.0.Alpha1

/**
 * SpecializationId generated by hbm2java
 */
public class SpecializationId extends Entity {
	private static final long serialVersionUID = -1853817634200093394L;
	private int specializationId;
	private int fieldOfStudyId;

	public SpecializationId() {
	}

	public SpecializationId(int specializationId, int fieldOfStudyId) {
		this.specializationId = specializationId;
		this.fieldOfStudyId = fieldOfStudyId;
	}

	public int getSpecializationId() {
		return this.specializationId;
	}

	public void setSpecializationId(int specializationId) {
		this.specializationId = specializationId;
	}

	public int getFieldOfStudyId() {
		return this.fieldOfStudyId;
	}

	public void setFieldOfStudyId(int fieldOfStudyId) {
		this.fieldOfStudyId = fieldOfStudyId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SpecializationId))
			return false;
		SpecializationId castOther = (SpecializationId) other;

		return (this.getSpecializationId() == castOther.getSpecializationId())
				&& (this.getFieldOfStudyId() == castOther.getFieldOfStudyId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getSpecializationId();
		result = 37 * result + this.getFieldOfStudyId();
		return result;
	}
}