package model.entity;
// Generated 2016-12-09 16:03:21 by Hibernate Tools 5.1.0.Alpha1

/**
 * StudentId generated by hbm2java
 */
public class StudentId extends Entity {
	private static final long serialVersionUID = -2876400998358585559L;
	private int studentId;
	private String userLogin;

	public StudentId() {
	}

	public StudentId(int studentId, String userLogin) {
		this.studentId = studentId;
		this.userLogin = userLogin;
	}

	public int getStudentId() {
		return this.studentId;
	}

	public void setStudentId(int studentId) {
		this.studentId = studentId;
	}

	public String getUserLogin() {
		return this.userLogin;
	}

	public void setUserLogin(String userLogin) {
		this.userLogin = userLogin;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StudentId))
			return false;
		StudentId castOther = (StudentId) other;

		return (this.getStudentId() == castOther.getStudentId())
				&& ((this.getUserLogin() == castOther.getUserLogin()) || (this.getUserLogin() != null
						&& castOther.getUserLogin() != null && this.getUserLogin().equals(castOther.getUserLogin())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getStudentId();
		result = 37 * result + (getUserLogin() == null ? 0 : this.getUserLogin().hashCode());
		return result;
	}
}