package model.entity;
// Generated 2016-12-09 16:03:21 by Hibernate Tools 5.1.0.Alpha1

/**
 * TeacherId generated by hbm2java
 */
public class TeacherId extends Entity {
	private static final long serialVersionUID = 8862181021497563523L;
	private int teacherId;
	private String userLogin;

	public TeacherId() {
	}

	public TeacherId(int teacherId, String userLogin) {
		this.teacherId = teacherId;
		this.userLogin = userLogin;
	}

	public int getTeacherId() {
		return this.teacherId;
	}

	public void setTeacherId(int teacherId) {
		this.teacherId = teacherId;
	}

	public String getUserLogin() {
		return this.userLogin;
	}

	public void setUserLogin(String userLogin) {
		this.userLogin = userLogin;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TeacherId))
			return false;
		TeacherId castOther = (TeacherId) other;

		return (this.getTeacherId() == castOther.getTeacherId())
				&& ((this.getUserLogin() == castOther.getUserLogin()) || (this.getUserLogin() != null
						&& castOther.getUserLogin() != null && this.getUserLogin().equals(castOther.getUserLogin())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getTeacherId();
		result = 37 * result + (getUserLogin() == null ? 0 : this.getUserLogin().hashCode());
		return result;
	}
}