package model.entity;
// Generated 2016-12-09 16:03:21 by Hibernate Tools 5.1.0.Alpha1

/**
 * Teacher generated by hbm2java
 */
public class Teacher extends Entity {
	private static final long serialVersionUID = 5284597566403337062L;
	private TeacherId id;
	private Integer addressId;
	private Integer departmentId;
	private Integer instituteId;
	private String teacherPhoto;
	private String teacherTitle;
	private String teacherFirstname;
	private String teacherSecondname;
	private String teacherLastname;
	private String teacherBirthdate;
	private String teacherPhone;
	private String teacherRoom;
	private String teacherWebsite;

	
	public Teacher() {}
	public Teacher(TeacherId id) {
		this.id = id;
	}
	public Teacher(TeacherId id, Integer addressId, Integer departmentId, Integer instituteId, String teacherPhoto,
			String teacherTitle, String teacherFirstname, String teacherSecondname, String teacherLastname, String teacherBirthdate,
			String teacherPhone, String teacherRoom, String teacherWebsite) {
		this.id = id;
		this.addressId = addressId;
		this.departmentId = departmentId;
		this.instituteId = instituteId;
		this.teacherPhoto = teacherPhoto;
		this.teacherTitle = teacherTitle;
		this.teacherFirstname = teacherFirstname;
		this.teacherSecondname = teacherSecondname;
		this.teacherLastname = teacherLastname;
		this.teacherBirthdate = teacherBirthdate;
		this.teacherPhone = teacherPhone;
		this.teacherRoom = teacherRoom;
		this.teacherWebsite = teacherWebsite;
	}
	public Teacher(int teacherId, String userLogin, Integer addressId, Integer departmentId, Integer instituteId, String teacherPhoto,
			String teacherTitle, String teacherFirstname, String teacherSecondname, String teacherLastname, String teacherBirthdate,
			String teacherPhone, String teacherRoom, String teacherWebsite) {
		this.id = new TeacherId(teacherId, userLogin);
		this.addressId = addressId;
		this.departmentId = departmentId;
		this.instituteId = instituteId;
		this.teacherPhoto = teacherPhoto;
		this.teacherTitle = teacherTitle;
		this.teacherFirstname = teacherFirstname;
		this.teacherSecondname = teacherSecondname;
		this.teacherLastname = teacherLastname;
		this.teacherBirthdate = teacherBirthdate;
		this.teacherPhone = teacherPhone;
		this.teacherRoom = teacherRoom;
		this.teacherWebsite = teacherWebsite;
	}
	

	public TeacherId getId() {
		return this.id;
	}
	public void setId(TeacherId id) {
		this.id = id;
	}
	public Integer getAddressId() {
		return this.addressId;
	}
	public void setAddressId(Integer addressId) {
		this.addressId = addressId;
	}
	public Integer getDepartmentId() {
		return this.departmentId;
	}
	public void setDepartmentId(Integer departmentId) {
		this.departmentId = departmentId;
	}
	public Integer getInstituteId() {
		return this.instituteId;
	}
	public void setInstituteId(Integer instituteId) {
		this.instituteId = instituteId;
	}
	public String getTeacherPhoto() {
		return this.teacherPhoto;
	}
	public void setTeacherPhoto(String teacherPhoto) {
		this.teacherPhoto = teacherPhoto;
	}
	public String getTeacherFirstname() {
		return this.teacherFirstname;
	}
	public void setTeacherFirstname(String teacherFirstname) {
		this.teacherFirstname = teacherFirstname;
	}
	public String getTeacherSecondname() {
		return this.teacherSecondname;
	}
	public void setTeacherSecondname(String teacherSecondname) {
		this.teacherSecondname = teacherSecondname;
	}
	public String getTeacherLastname() {
		return this.teacherLastname;
	}
	public void setTeacherLastname(String teacherLastname) {
		this.teacherLastname = teacherLastname;
	}
	public String getTeacherBirthdate() {
		return this.teacherBirthdate;
	}
	public void setTeacherBirthdate(String teacherBirthdate) {
		this.teacherBirthdate = teacherBirthdate;
	}
	public String getTeacherPhone() {
		return this.teacherPhone;
	}
	public void setTeacherPhone(String teacherPhone) {
		this.teacherPhone = teacherPhone;
	}
	public String getTeacherRoom() {
		return this.teacherRoom;
	}
	public void setTeacherRoom(String teacherRoom) {
		this.teacherRoom = teacherRoom;
	}
	public String getTeacherWebsite() {
		return this.teacherWebsite;
	}
	public void setTeacherWebsite(String teacherWebsite) {
		this.teacherWebsite = teacherWebsite;
	}
	public String getTeacherTitle() {
		return teacherTitle;
	}
	public void setTeacherTitle(String teacherTitle) {
		this.teacherTitle = teacherTitle;
	}
}