package model.entity;
// Generated 2016-12-09 16:03:21 by Hibernate Tools 5.1.0.Alpha1

/**
 * TeacherId generated by hbm2java
 */
public class TeacherId implements java.io.Serializable {
	private static final long serialVersionUID = 8862181021497563523L;
	private int teacherId;
	private int userId;

	
	public TeacherId() {}
	public TeacherId(int teacherId, int userId) {
		this.teacherId = teacherId;
		this.userId = userId;
	}

	
	public int getTeacherId() {
		return this.teacherId;
	}
	public void setTeacherId(int teacherId) {
		this.teacherId = teacherId;
	}
	public int getUserId() {
		return this.userId;
	}
	public void setUserId(int userId) {
		this.userId = userId;
	}
	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TeacherId))
			return false;
		TeacherId castOther = (TeacherId) other;

		return (this.getTeacherId() == castOther.getTeacherId()) && (this.getUserId() == castOther.getUserId());
	}
	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getTeacherId();
		result = 37 * result + this.getUserId();
		return result;
	}
}