package model.entity;
// Generated 2016-12-08 01:23:57 by Hibernate Tools 5.1.0.Alpha1

/**
 * TeachersCoursesId generated by hbm2java
 */
public class TeachersCoursesId extends Entity {
	private static final long serialVersionUID = -8441083904027712888L;
	private int teacherId;
	private int courseId;

	public TeachersCoursesId() {
	}

	public TeachersCoursesId(int teacherId, int courseId) {
		this.teacherId = teacherId;
		this.courseId = courseId;
	}

	public int getTeacherId() {
		return this.teacherId;
	}

	public void setTeacherId(int teacherId) {
		this.teacherId = teacherId;
	}

	public int getCourseId() {
		return this.courseId;
	}

	public void setCourseId(int courseId) {
		this.courseId = courseId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TeachersCoursesId))
			return false;
		TeachersCoursesId castOther = (TeachersCoursesId) other;

		return (this.getTeacherId() == castOther.getTeacherId()) && (this.getCourseId() == castOther.getCourseId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getTeacherId();
		result = 37 * result + this.getCourseId();
		return result;
	}
}