package model.entity;
// Generated 2016-12-09 16:03:21 by Hibernate Tools 5.1.0.Alpha1

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {
	private static final long serialVersionUID = -2466757679109947635L;
	private int userId;
	private String userLogin;
	private String userPassword;
	private String userEmail;
	private String userType;

	
	public User() {}
	public User(int userId) {
		this.userId = userId;
	}
	public User(int userId, String userLogin, String userPassword, String userEmail, String userType) {
		this.userId = userId;
		this.userLogin = userLogin;
		this.userPassword = userPassword;
		this.userEmail = userEmail;
		this.userType = userType;
	}

	
	public int getUserId() {
		return this.userId;
	}
	public void setUserId(int userId) {
		this.userId = userId;
	}
	public String getUserLogin() {
		return this.userLogin;
	}
	public void setUserLogin(String userLogin) {
		this.userLogin = userLogin;
	}
	public String getUserPassword() {
		return this.userPassword;
	}
	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}
	public String getUserEmail() {
		return this.userEmail;
	}
	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}
	public String getUserType() {
		return this.userType;
	}
	public void setUserType(String userType) {
		this.userType = userType;
	}
}